In [1]:
pip install kafka-python

Collecting kafka-python
  Downloading kafka_python-2.0.2-py2.py3-none-any.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.5/246.5 kB 2.7 MB/s eta 0:00:0000:0100:01
Installing collected packages: kafka-python
Successfully installed kafka-python-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [15]:
pip install s3fs

Collecting s3fs
  Downloading s3fs-2023.1.0-py3-none-any.whl (27 kB)
Collecting fsspec==2023.1.0
  Downloading fsspec-2023.1.0-py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 1.8 MB/s eta 0:00:00a 0:00:01
Collecting aiobotocore~=2.4.2
  Downloading aiobotocore-2.4.2-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 2.3 MB/s eta 0:00:00
Collecting aiohttp!=4.0.0a0,!=4.0.0a1
  Downloading aiohttp-3.8.3-cp39-cp39-macosx_10_9_x86_64.whl (360 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 360.7/360.7 kB 4.0 MB/s eta 0:00:0000:0100:01
Collecting aioitertools>=0.5.1
  Downloading aioitertools-0.11.0-py3-none-any.whl (23 kB)
Requirement already satisfied: wrapt>=1.10.10 in /Users/ashwinpandey/opt/anaconda3/lib/python3.9/site-packages (from aiobotocore~=2.4.2->s3fs) (1.14.1)
Collecting botocore<1.27.60,>=1.27.59
  Downloading botocore-1.27.59-py3-none-any.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 16.7 MB/s eta 0:00:0000:0100:01
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp39-cp39-macosx_10_9_x86_64.whl (29 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Requirement already satisfied: attrs>=17.3.0 in /Users/ashwinpandey/opt/anaconda3/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (21.4.0)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.3-cp39-cp39-macosx_10_9_x86_64.whl (36 kB)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /Users/ashwinpandey/opt/anaconda3/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (2.0.4)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.8.2-cp39-cp39-macosx_10_9_x86_64.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: typing_extensions>=4.0 in /Users/ashwinpandey/opt/anaconda3/lib/python3.9/site-packages (from aioitertools>=0.5.1->aiobotocore~=2.4.2->s3fs) (4.3.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /Users/ashwinpandey/opt/anaconda3/lib/python3.9/site-packages (from botocore<1.27.60,>=1.27.59->aiobotocore~=2.4.2->s3fs) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /Users/ashwinpandey/opt/anaconda3/lib/python3.9/site-packages (from botocore<1.27.60,>=1.27.59->aiobotocore~=2.4.2->s3fs) (1.26.11)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /Users/ashwinpandey/opt/anaconda3/lib/python3.9/site-packages (from botocore<1.27.60,>=1.27.59->aiobotocore~=2.4.2->s3fs) (0.10.0)
Requirement already satisfied: idna>=2.0 in /Users/ashwinpandey/opt/anaconda3/lib/python3.9/site-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (3.3)
Requirement already satisfied: six>=1.5 in /Users/ashwinpandey/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.27.60,>=1.27.59->aiobotocore~=2.4.2->s3fs) (1.16.0)
Installing collected packages: multidict, fsspec, frozenlist, async-timeout, aioitertools, yarl, botocore, aiosignal, aiohttp, aiobotocore, s3fs
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2022.7.1
    Uninstalling fsspec-2022.7.1:
      Successfully uninstalled fsspec-2022.7.1
  Attempting uninstall: botocore
    Found existing installation: botocore 1.27.28
    Uninstalling botocore-1.27.28:
      Successfully uninstalled botocore-1.27.28
Successfully installed aiobotocore-2.4.2 aiohttp-3.8.3 aioitertools-0.11.0 aiosignal-1.3.1 async-timeout-4.0.2 botocore-1.27.59 frozenlist-1.3.3 fsspec-2023.1.0 multidict-6.0.4 s3fs-2023.1.0 yarl-1.8.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
from kafka import KafkaConsumer, KafkaProducer
from time import sleep
from json import dumps
import json

In [2]:
producer = KafkaProducer(bootstrap_servers=['3.111.31.123:9092'], #change ip here 3.111.31.123
                         value_serializer=lambda x: 
                         dumps(x).encode('utf-8'))

In [3]:
producer.send('demo_testing2', value={'ram':'ram'})

In [4]:
df=pd.read_csv("data.txt")

In [5]:
df

,Index,Date,Open,High,Low,Close,Adj Close,Volume,CloseUSD
0,HSI,1986-12-31,2568.300049,2568.300049,2568.300049,2568.300049,2568.300049,0.000000e+00,333.879006
1,HSI,1987-01-02,2540.100098,2540.100098,2540.100098,2540.100098,2540.100098,0.000000e+00,330.213013
2,HSI,1987-01-05,2552.399902,2552.399902,2552.399902,2552.399902,2552.399902,0.000000e+00,331.811987
3,HSI,1987-01-06,2583.899902,2583.899902,2583.899902,2583.899902,2583.899902,0.000000e+00,335.906987
4,HSI,1987-01-07,2607.100098,2607.100098,2607.100098,2607.100098,2607.100098,0.000000e+00,338.923013
...,...,...,...,...,...,...,...,...,...
34443,IXIC,2018-09-07,7878.790039,7962.529785,7873.930176,7902.540039,7902.540039,2.146380e+09,7902.540039
34444,IXIC,2018-09-10,7939.569824,7945.029785,7890.390137,7924.160156,7924.160156,2.041450e+09,7924.160156
34445,IXIC,2018-09-11,7894.870117,7986.319824,7880.919922,7972.470215,7972.470215,2.336600e+09,7972.470215
34446,IXIC,2018-09-12,7958.870117,7965.390137,7884.049805,7954.229980,7954.229980,2.341850e+09,7954.229980
34447,IXIC,2018-09-13,7999.930176,8037.509766,7989.850098,8013.709961,8013.709961,2.318720e+09,8013.709961

In [6]:
df.sample(5)

,Index,Date,Open,High,Low,Close,Adj Close,Volume,CloseUSD
30302,IXIC,2002-03-28,1836.250000,1852.849976,1833.329956,1845.349976,1845.349976,1.664900e+09,1845.349976
9545,NYA,1970-04-20,501.089996,501.089996,501.089996,501.089996,501.089996,0.000000e+00,501.089996
26083,IXIC,1985-07-10,297.600006,298.500000,297.100006,298.500000,298.500000,7.715000e+07,298.500000
11732,NYA,1978-12-13,568.020020,568.020020,568.020020,568.020020,568.020020,0.000000e+00,568.020020
33702,IXIC,2015-09-29,4551.040039,4596.060059,4487.060059,4517.319824,4517.319824,2.293450e+09,4517.319824

In [8]:
while True:
    dict_stock = df.sample(1).to_dict(orient="records")[0]
    producer.send('demo_testing2', value=dict_stock)
    sleep(2)

KeyboardInterrupt: